language: go

go:
  - "1.x"
  - master

env:
- GO111MODULE=on

script:
  - test -z $(gofmt -l -s *.go)
  - go test -v -coverprofile=cover.out -covermode=atomic -race
  - bash <(curl -s https://codecov.io/bash)
